### ISSUE TITLE
faq

### ISSUE THREAD

**Issue by willis-yang** [woyehenni/ipatool#1]
Which version of iTunes did you use to do the packet capture?

**Comment by woyehenni** [comment]
@willis-yang 

iTunes for windows v12.6.5.3
Other versions will not work.

**Comment by woyehenni** [comment]
The Mac version doesn't work too.

**Comment by willis-yang** [comment]
ok,but,using this v12.6.5.3 ,i see itunes had change his download method ,they using this method only
![image](https://github.com/user-attachments/assets/fd3f8d84-a153-473c-a81d-60ee993a0e69)

**Comment by woyehenni** [comment]
I didn't do any packet capture, I referred to this code: https://github.com/beer-psi/ipatool.ts

**Comment by woyehenni** [comment]
If you have purchased an app in the app store of that country before, you can download it directly. Otherwise, you need to call the API you prompted to purchase it first.

https://github.com/beer-psi/ipatool.ts/blob/trunk/src/store-api/store/endpoint.ts#L11C6-L11C69
